### PR TITLE
Revamp entire distrolist homepage

### PR DESCRIPTION
**Pull request by jakiisheep**

### CODE REVIEW

**Comment by jakiisheep** [comment]
@paledega ?

**Comment by jakiisheep** [comment]
Nevermind, this project is probably abandoned.

**Comment by paledega** [comment]
This project is not abandoned yet :D

**Comment by jakiisheep** [comment]
Sorry, I thought it was.

> This project is not abandoned yet :D

**Comment by jakiisheep** [comment]
> [4eddaa7](https://github.com/distrolist/distrolist.github.io/commit/4eddaa77aed93e6462f40ba2b1559a5fcb10bd12)

Thanks for adding it!

**Pull request closed without merging**
